run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofumpt
    - gci
    - revive
    - staticcheck
    - govet
    - errcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - misspell
    - unconvert

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/jprybylski/datum)
  revive:
    rules:
      - name: exported
        disabled: true  # Don't require comments on all exported items

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
