version: 1
defaults:
  policy: fail
  algo: sha256

datasets:
  - id: google_uuid_license
    desc: "LICENSE from github.com/google/uuid (branch: main)"
    source:
      type: git
      url: https://github.com/google/uuid.git
      ref: main
      path: LICENSE
    target: data/ref/google_uuid_LICENSE.txt
    policy: fail
