// Command genschema converts the authored data-schema.json into Go source for the datum binary.
package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
)

func main() {
	os.Exit(run("data-schema.json", "schema_generated.go", os.Stderr))
}

func run(inputPath, outputPath string, stderr io.Writer) int {
	if err := generate(inputPath, outputPath); err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	return 0
}

func generate(inputPath, outputPath string) error {
	data, err := os.ReadFile(inputPath)
	if err != nil {
		return err
	}
	generated := "// Code generated by go generate; DO NOT EDIT.\n\npackage datum\n\nconst configSchema = " + strconv.Quote(string(data)) + "\n"
	return os.WriteFile(outputPath, []byte(generated), 0o644)
}
