// Command genschema converts the authored data-schema.json into Go source for the datum binary.
package main

import (
	"fmt"
	"os"
	"strconv"
)

func main() {
	data, err := os.ReadFile("data-schema.json")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	generated := "// Code generated by go generate; DO NOT EDIT.\n\npackage datum\n\nconst configSchema = " + strconv.Quote(string(data)) + "\n"
	if err := os.WriteFile("schema_generated.go", []byte(generated), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
